In [140]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import RandomForestRegressor
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix,accuracy_score

In [141]:
df=pd.read_csv('FDP1.csv')
df

           Restaurant Name        Cuisine  Distance   ETD
0             Café Niloufer        Bakery        5.5   29
1   Sri Raghavendra Tiffins  South Indian        3.9   21
2              Ram Ki Bandi  South Indian        5.0   25
3         Anu Tiffin Centre  South Indian        7.8   35
4      Sri ram Dosa Darbar   South Indian        5.5   28
5       Minerva Coffee Shop     Beverages        6.9   31
6            Hotel Suprabat        Kebabs        4.0   22
7      Sri Gayatri Tiffins   South Indian        3.7   20
8             Swiss Castle         Bakery        2.5   17
9              Alpha Hotel        Biryani        9.0   38
10                      RRR       Biryani        5.9   33
11            Shahi Zaikwa        Biryani        8.3   50
12       Ashoka Restaurant        Biryani        9.5   40
13             Nrs Nandhini       Biryani        4.4   22
14              Friutoholic        Juices        3.7   28
15       ThickShake Factory        Juices        6.5   33
16               CreamStone     Beverages        9.8   36
17                Pizza Hut        Pizzas        3.5   32
18              Slay Coffee     Beverages        6.3   45
19          Natural Fruits         Juices        3.5   21
20        Milkshakes Outlet     Beverages        5.0   32
21             Bombay Juice        Juices        7.9   38
22                   Faasos        Kebabs        3.0   24
23                 Barista      Beverages        6.3   33
24                 FB Cakes        Bakery        4.1   45
25      Chai Toh Banthi Hai     Beverages        6.9   45
26                   Dostea     Beverages       11.6   56
27                   Subway      Sandwich        3.5   25
28                KS Bakers      Sandwich        5.8   27

In [142]:
from sklearn.preprocessing import LabelEncoder 
le=LabelEncoder()
d=le.fit_transform(df['Cuisine'])
d

array([0, 7, 7, 7, 7, 1, 4, 7, 0, 2, 2, 2, 2, 2, 3, 3, 1, 5, 1, 3, 1, 3,
       4, 1, 0, 1, 1, 6, 6])

In [143]:
df['Cuisine']=d
df

           Restaurant Name   Cuisine  Distance   ETD
0             Café Niloufer        0        5.5   29
1   Sri Raghavendra Tiffins        7        3.9   21
2              Ram Ki Bandi        7        5.0   25
3         Anu Tiffin Centre        7        7.8   35
4      Sri ram Dosa Darbar         7        5.5   28
5       Minerva Coffee Shop        1        6.9   31
6            Hotel Suprabat        4        4.0   22
7      Sri Gayatri Tiffins         7        3.7   20
8             Swiss Castle         0        2.5   17
9              Alpha Hotel         2        9.0   38
10                      RRR        2        5.9   33
11            Shahi Zaikwa         2        8.3   50
12       Ashoka Restaurant         2        9.5   40
13             Nrs Nandhini        2        4.4   22
14              Friutoholic        3        3.7   28
15       ThickShake Factory        3        6.5   33
16               CreamStone        1        9.8   36
17                Pizza Hut        5        3.5   32
18              Slay Coffee        1        6.3   45
19          Natural Fruits         3        3.5   21
20        Milkshakes Outlet        1        5.0   32
21             Bombay Juice        3        7.9   38
22                   Faasos        4        3.0   24
23                 Barista         1        6.3   33
24                 FB Cakes        0        4.1   45
25      Chai Toh Banthi Hai        1        6.9   45
26                   Dostea        1       11.6   56
27                   Subway        6        3.5   25
28                KS Bakers        6        5.8   27

In [144]:
x=df.iloc[:,[1,2]]
x

    Cuisine  Distance
0         0        5.5
1         7        3.9
2         7        5.0
3         7        7.8
4         7        5.5
5         1        6.9
6         4        4.0
7         7        3.7
8         0        2.5
9         2        9.0
10        2        5.9
11        2        8.3
12        2        9.5
13        2        4.4
14        3        3.7
15        3        6.5
16        1        9.8
17        5        3.5
18        1        6.3
19        3        3.5
20        1        5.0
21        3        7.9
22        4        3.0
23        1        6.3
24        0        4.1
25        1        6.9
26        1       11.6
27        6        3.5
28        6        5.8

In [145]:
y=df.iloc[:,3]
y

0     29
1     21
2     25
3     35
4     28
5     31
6     22
7     20
8     17
9     38
10    33
11    50
12    40
13    22
14    28
15    33
16    36
17    32
18    45
19    21
20    32
21    38
22    24
23    33
24    45
25    45
26    56
27    25
28    27
Name: ETD, dtype: int64

In [160]:
#x_train,x_test,y_train,y_test=train_test_split(x,y)
#st=StandardScaler()
#x_train=st.fit_transform(x_train)
#x_test=st.transform(x_test)

In [161]:
forest=RandomForestRegressor(n_estimators=10,random_state=42,oob_score=True)
forest.fit(x,y)

RandomForestRegressor(n_estimators=10, oob_score=True, random_state=42)

In [162]:
y_pred=forest.predict(x)

In [163]:
y_pred

array([30.7       , 23.8       , 25.6       , 33.8       , 27.4       ,
       37.66666667, 26.3       , 21.4       , 23.3       , 38.8       ,
       31.4       , 46.4       , 39.2       , 26.6       , 26.6       ,
       31.7       , 40.6       , 29.4       , 38.        , 22.8       ,
       27.        , 34.5       , 22.5       , 38.        , 37.1       ,
       37.66666667, 50.2       , 25.4       , 27.6       ])